\input texinfo

@settitle OctApps Reference Manual

@copying
This document is the reference manual for OctApps.

Copyright @copyright{} 2018 The Authors of OctApps.

@quotation
Copying and distribution of this document, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
@end quotation
@end copying

@contents

@node Top
@top OctApps Reference Manual

@emph{OctApps} provides various functions intended to aid research scientists who perform searches for continuous gravitational waves.
In also provides various general-purpose functions which may be of broader interest to users of Octave.
Please see the @url{https://github.com/octapps/octapps, project homepage} for further information on @emph{OctApps}.

@menu
* Directory Index::     Functions in each @emph{OctApps} directory.
* Function Index::      Index of all functions in @emph{OctApps}.
@end menu

@node Directory Index
@chapter Directory Index
@include directory-index-menu.texi
@include directory-index.texi

@node Function Index
@chapter Function Index
@printindex fn

@bye
