\input texinfo

@settitle OctApps Reference Manual

@copying
This document is the reference manual for OctApps.

Copyright @copyright{} 2018 The Authors of OctApps.

@quotation
Copying and distribution of this document, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
@end quotation
@end copying

@contents

@node Top
@top OctApps Reference Manual

@emph{OctApps} provides various functions intended to aid research scientists who perform searches for continuous gravitational waves.
In also provides various general-purpose functions which may be of broader interest to users of Octave.
Please see the @url{https://github.com/octapps/octapps, project homepage} for further information on @emph{OctApps}.

This manual provides a series of @ref{Tutorials, tutorials} which illustrate some of the functionality of @emph{OctApps}.
It also provides indexes of @emph{OctApps} functions organised by @ref{Directory Index, directory}, as well as @ref{Function Index, alphabetically}.

This manual was last generated on @today{}.

@heading Acknowledgement

If you make use of @emph{OctApps}, please cite our @url{https://doi.org/10.21105/joss.00707,paper} in the @url{http://joss.theoj.org,Journal of Open Source Software}:

@verbatim
@article{octapps,
  author = {Karl Wette and Reinhard Prix and David Keitel and Matthew Pitkin and Christoph Dreissigacker and John T. Whelan and Paola Leaci},
  title = {{OctApps: a library of Octave functions for continuous gravitational-wave data analysis}},
  journal = {Journal of Open Source Software},
  year = {2018},
  volume = {3},
  number = {26},
  pages = {707},
  doi = {10.21105/joss.00707},
}
@end verbatim

@heading Chapters

@menu
* Tutorials::           Tutorials illustrating @emph{OctApps} functionality.
* Directory Index::     Functions in each @emph{OctApps} directory.
* Function Index::      Index of all functions in @emph{OctApps}.
@end menu

@node Tutorials
@chapter Tutorials
@include tutorials.texi

@node Directory Index
@chapter Directory Index
@include directory-index-menu.texi
@include directory-index.texi

@node Function Index
@chapter Function Index
@printindex fn

@bye
